import { BaseMessage } from "@langchain/core/messages";

export interface AgentState {
    // User context
    userProfile: {
        user_type?: 'business' | 'pre_entrepreneur' | 'researcher' | 'other';
        industry?: string;
        location?: string;
        techStack?: string[];
        research_keywords?: string[];
        [key: string]: any;
    };

    // Real-time market indicators
    economicData: {
        usdKrw?: number;
        kospi?: number;
        kosdaq?: number;
        lastUpdated?: number;
        [key: string]: any;
    };

    // File Analysis (Context from uploaded documents)
    uploadedFileContent: string;

    // Selection from HITL (Grant Selection)
    selectedGrant?: {
        id: string;
        title: string;
        description: string;
        requirements: string;
    };

    // Research & Fact-finding (Perplexity)
    researchFindings: string;

    // Thought expansion (Genspark logic)
    expandedThoughts: string[];

    // Specialist model outputs
    outputs: {
        strategy?: string;  // Generated by Gemini 1.5 Pro
        writer?: string;    // Generated by Claude 3.5 Sonnet
        visualizer?: string; // Generated by Gemini 1.5 Pro
        [key: string]: any;
    };

    // LangGraph internal state
    messages: BaseMessage[];
}
