import { BaseMessage } from "@langchain/core/messages";

export interface BusinessIdea {
    description: string;      // 사업 아이디어 설명
    teamComposition: string;  // 팀 구성
    currentStage: string;     // 현재 단계 (아이디어/프로토타입/매출발생)
    targetMarket: string;     // 타겟 시장
    differentiator: string;   // 차별점
}

export interface GrantAttachment {
    fileName: string;
    downloadUrl: string;
    pdfPreviewCode?: string;
    fileType: string; // "hwp" | "pdf" | "docx"
}

export interface GrantDocuments {
    attachments: GrantAttachment[];
    formStructure: string[];  // AI가 추출한 양식 항목 목록
    requirements: string;     // 제출 요건 텍스트
    announcementBody: string; // 공고 본문 전체
}

export interface AgentState {
    // User context
    userProfile: {
        user_type?: 'business' | 'pre_entrepreneur' | 'researcher' | 'other';
        industry?: string;
        location?: string;
        techStack?: string[];
        research_keywords?: string[];
        [key: string]: any;
    };

    // Real-time market indicators
    economicData: {
        usdKrw?: number;
        kospi?: number;
        kosdaq?: number;
        lastUpdated?: number;
        [key: string]: any;
    };

    // File Analysis (Context from uploaded documents)
    uploadedFileContent: string;

    // Selection from HITL (Grant Selection)
    selectedGrant?: {
        id: string;
        title: string;
        description: string;
        requirements: string;
        application_url?: string;
        [key: string]: any;
    };

    // HITL: User's business idea (Step 3)
    businessIdea?: BusinessIdea;

    // Fetched grant documents & form structure (Step 4)
    grantDocuments?: GrantDocuments;

    // Research & Fact-finding (Perplexity)
    researchFindings: string;

    // Thought expansion (Genspark logic)
    expandedThoughts: string[];

    // Specialist model outputs
    outputs: {
        strategy?: string;     // Generated by Strategist
        writer?: string;       // Generated by Writer (full or section-based)
        writerSections?: Record<string, string>; // Section-by-section drafts
        visualizer?: string;   // Generated by Visualizer
        [key: string]: any;
    };

    // LangGraph internal state
    messages: BaseMessage[];
}
