-- Migration: Replace fake seed grants with real K-Startup data
-- Source: https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do (2026-03-04)

-- First, remove all fake seed data
DELETE FROM public.grants WHERE source = 'seed' OR source IS NULL OR source = 'manual';

-- Insert real grants from K-Startup (모집중 as of 2026-03-04)
INSERT INTO public.grants (title, agency, d_day, target_audience, tech_field, summary, category, description, original_url, link, region, department, application_period, source)
VALUES 
(
    '2026년도 예비창업패키지 예비창업자 모집 수정 공고',
    '창업진흥원',
    'D-20',
    '예비창업자',
    '전분야',
    '예비창업자의 사업계획서 기반 창업사업화를 지원하는 대표적인 창업지원사업',
    'Commercialization',
    '예비창업자 대상 최대 1억원 창업사업화 자금 지원. 기술 기반 사업 아이디어를 가진 예비창업자가 성공적으로 창업할 수 있도록 사업화 자금, 교육, 멘토링 등을 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176458',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176458',
    '전국',
    '중소벤처기업부',
    '2026-02 ~ 2026-03-24',
    'k-startup'
),
(
    '2026년 글로벌기업 협업프로그램 창업기업 모집 공고',
    '창업진흥원',
    'D-12',
    '스타트업',
    '전분야',
    '글로벌 대기업과 국내 스타트업의 협업을 통한 해외 시장 진출 지원',
    'Commercialization',
    '글로벌 대기업과 국내 스타트업 간 협업 프로그램을 통해 해외 시장 진출을 지원합니다. 파트너 기업과의 공동 프로젝트, 해외 판로 개척 등을 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176467',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176467',
    '전국',
    '중소벤처기업부',
    '~ 2026-03-16',
    'k-startup'
),
(
    '2026년도 글로벌 액셀러레이팅(GMEP) 지원사업 창업기업 모집공고',
    '창업진흥원',
    'D-27',
    '스타트업',
    '전분야',
    '글로벌 액셀러레이팅 프로그램을 통한 해외 진출 지원',
    'Commercialization',
    '글로벌 시장 진출을 희망하는 창업기업을 대상으로 현지 액셀러레이팅 프로그램, 데모데이, 투자 연계 등을 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176429',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176429',
    '전국',
    '중소벤처기업부',
    '~ 2026-03-31',
    'k-startup'
),
(
    '2026년 「민관협력 오픈이노베이션 지원」방산 스타트업 챌린지 스타트업 모집공고',
    '창업진흥원',
    'D-7',
    '스타트업',
    '방위산업, 국방',
    '민관협력 기반 방산 분야 스타트업 도전 프로그램',
    'Commercialization',
    '민관협력을 통한 방위산업 분야 혁신 스타트업을 발굴하고 지원합니다. 방산 대기업과의 협력 기회를 제공합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176358',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176358',
    '전국',
    '중소벤처기업부',
    '~ 2026-03-11',
    'k-startup'
),
(
    '2026년 「민관협력 오픈이노베이션 지원」전략과제 해결형(Top-Down) 스타트업 모집공고',
    '창업진흥원',
    'D-15',
    '스타트업',
    '전분야',
    '대기업 전략 과제를 스타트업과 함께 해결하는 오픈이노베이션 프로그램',
    'Commercialization',
    '대기업이 제시하는 전략과제를 스타트업의 혁신 기술로 해결하는 프로그램입니다. 협업 성과에 따른 투자/납품 연계를 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176341',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176341',
    '전국',
    '중소벤처기업부',
    '~ 2026-03-19',
    'k-startup'
),
(
    '2026년도 창업중심대학 지역기반 (예비)창업기업 모집공고',
    '창업진흥원',
    'D-19',
    '예비창업자, 초기 스타트업',
    '전분야',
    '창업중심대학을 통한 지역 기반 창업 지원 프로그램',
    'Commercialization',
    '창업중심대학 기반 지역 예비창업자 및 초기 창업기업을 대상으로 사업화 자금, 창업 교육, 멘토링 등을 종합 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176503',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176503',
    '전국',
    '중소벤처기업부',
    '2026-03-03 ~ 2026-03-23',
    'k-startup'
),
(
    '2026년도 창업중심대학 대학발 (예비)창업기업 모집 공고',
    '창업진흥원',
    'D-19',
    '예비창업자, 대학 기반 창업자',
    '전분야',
    '대학 기술 또는 아이디어 기반 창업 기업 지원 프로그램',
    'Commercialization',
    '대학의 우수 기술과 아이디어를 기반으로 창업하려는 예비창업자 및 초기 창업기업을 사업화 자금, 교육, 멘토링 등으로 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176498',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176498',
    '전국',
    '중소벤처기업부',
    '2026-03-03 ~ 2026-03-23',
    'k-startup'
),
(
    '2026년 팁스(TIPS) 창업기업 지원계획 공고',
    '창업진흥원',
    'D-302',
    '초기 스타트업',
    '전분야',
    '민간 투자 주도형 기술 창업 지원 프로그램 (엔젤투자 + R&D 자금)',
    'R&D',
    'TIPS는 민간 투자자(운영사)가 유망 기술 창업팀을 발굴하여 엔젤투자를 하고, 정부가 R&D 자금을 매칭 지원하는 프로그램입니다. 최대 5억원 R&D 자금을 지원합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176076',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176076',
    '전국',
    '중소벤처기업부',
    '상시 ~ 2026-12-31',
    'k-startup'
),
(
    '2026년 중앙부처 및 지자체 창업지원사업 통합공고',
    '창업진흥원',
    'D-302',
    '예비창업자, 스타트업, 중소기업',
    '전분야',
    '중앙부처 및 지자체의 창업지원사업을 한눈에 확인할 수 있는 통합 공고',
    'Commercialization',
    '2026년 중앙부처 및 지방자치단체에서 시행하는 창업지원사업을 통합하여 공고합니다. 개별 사업의 상세 내용은 각 기관 홈페이지를 참조해주세요.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=175783',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=175783',
    '전국',
    '중소벤처기업부',
    '~ 2026-12-31',
    'k-startup'
),
(
    '2026 메이커스페이스 전문랩 창업공간 입주기업 모집공고',
    '차세대융합기술연구원',
    'D-9',
    '스타트업',
    '하드웨어, 제조',
    '메이커스페이스 전문랩 입주 기업을 모집하여 창업 공간과 장비를 제공',
    'Commercialization',
    '메이커스페이스 전문랩에 입주하여 시제품 제작, 장비 활용, 전문가 멘토링 등을 받을 수 있는 창업공간 입주기업을 모집합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176457',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176457',
    '경기',
    '차세대융합기술연구원',
    '2026-03-03 ~ 2026-03-13',
    'k-startup'
),
(
    '[창업진흥원] 2026년도 K-StartHub 입주기업 모집공고',
    '창업진흥원',
    'D-2',
    '스타트업',
    '전분야',
    'K-StartHub 입주 기업 모집 - 창업 보육 공간 및 지원 프로그램 제공',
    'Commercialization',
    'K-StartHub는 유망 스타트업에게 사무 공간, 네트워킹, 멘토링, 투자 연계 등 종합 지원을 제공하는 프로그램입니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176114',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176114',
    '전국',
    '중소벤처기업부',
    '~ 2026-03-06',
    'k-startup'
),
(
    '창업지원사업 예비위원단 재모집 (신산업분야)',
    '창업진흥원',
    'D-271',
    '전문가, 심사위원',
    '신산업',
    '창업지원사업 심사/평가를 위한 예비위원 모집',
    'Commercialization',
    '중소벤처기업부 창업지원사업의 평가, 심사, 멘토링 활동에 참여할 신산업 분야 전문가를 예비위원으로 모집합니다.',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176391',
    'https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do?schM=view&pbancSn=176391',
    '전국',
    '중소벤처기업부',
    '~ 2026-11-30',
    'k-startup'
);
